# End-to-end test on the BUNDLED example dataset, starting from the files that
# actually ship with the package: record_data_input.xlsx and the Bacon .out files.
#
# Full pipeline exercised (no Bacon run, no rbacon needed -- load_event_ages() reads
# the .out files directly and interpolates deterministically):
#   read_record_data() -> load_event_ages() -> process_event_ages() -> compute_synchronicity_values()
#
# The reference result lives in Example/SyncER_outputs/synchro-test_stats.csv
# (regenerated by the workflow, not shipped). This test does NOT hard-pin those
# exact Monte Carlo numbers; instead it asserts the properties that must hold for
# the method to be working -- above all the paper's central claim: the correctly
# correlated "synchro-test" horizons out-score every pairing that involves the
# deliberately mismatched "synchro-test-wrong" layer -- plus loose bounds around
# the recorded scores. These are robust to seed/offset/n_samples details.
#
# offset uses bp_datum() (current year - 1950), matching the workflow default, so
# the test keeps functioning as the calendar year advances. The loose bounds below
# absorb the small score drift this introduces from one year to the next.
REF_OFFSET <- bp_datum()

# Locate a directory holding the shipped inputs: record_data_input.xlsx alongside
# per-record Bacon folders (core1/, ...) that contain .out files. Prefers an
# installed inst/extdata/ copy (works under R CMD check); falls back to the
# source-tree Example/ folder.
find_example_dir <- function() {
  has_inputs <- function(d) {
    nzchar(d) &&
      file.exists(file.path(d, "record_data_input.xlsx")) &&
      length(list.files(d, pattern = "[0-9]\\.out$", recursive = TRUE)) > 0
  }
  installed <- system.file("extdata", package = "SyncER")
  if (has_inputs(installed)) return(installed)
  candidates <- c(
    testthat::test_path("..", "..", "Example"),
    testthat::test_path("..", "..", "..", "Example")
  )
  for (d in candidates) if (has_inputs(d)) return(normalizePath(d))
  NA_character_
}

# Extract synchro-test event ages from the original (non-synced) core models and
# reduce to the per-record posterior samples compute_synchronicity_values() consumes.
build_event_stats <- function(dir) {
  input <- suppressMessages(read_record_data(
    folder_path = dir, file_name = "record_data_input.xlsx"
  ))
  out_data <- suppressWarnings(suppressMessages(load_event_ages(
    folder_path   = dir,
    record_data   = input$record_data,
    event_types   = c("synchro-test"),
    max_depths    = input$max_depths,
    isochrons     = character(0),
    test_horizons = c("synchro-test"),
    synced        = "",
    thick         = 2
  )))
  process_event_ages(out_data, event_deposits = "synchro-test", offset = REF_OFFSET)
}

run_compute <- function(event_stats) {
  compute_synchronicity_values(
    event_stats,
    event_names      = "synchro-test",
    confidence_level = 0.95,
    age_difference   = 0.07,
    horizon_groups   = list("synchro-test" = c("synchro-test", "synchro-test-wrong"))
  )
}

# Pull one score out of the flat stats table by record pair + variant pair.
pair_score <- function(stats, r1, r2, v1, v2) {
  hit <- stats[stats$record1 == r1 & stats$record2 == r2 &
               stats$variant1 == v1 & stats$variant2 == v2, "synchronicity_score"]
  if (length(hit) == 1) hit else NA_real_
}

test_that("bundled run: .out files -> event ages -> synchronicity scores", {
  skip_on_cran()
  dir <- find_example_dir()
  skip_if(is.na(dir),
          "Bundled record_data_input.xlsx + .out files not found; ship them in inst/extdata to enable.")

  event_stats <- build_event_stats(dir)

  # The extraction actually produced the tested horizon across records.
  processed_cols <- unique(unlist(lapply(event_stats$processed, colnames)))
  expect_true("synchro-test" %in% processed_cols)

  res   <- run_compute(event_stats)
  stats <- res$all_horizon_stats

  # Every score is a valid probability.
  expect_true(all(stats$synchronicity_score >= 0 &
                  stats$synchronicity_score <= 1, na.rm = TRUE))

  # --- The method's central claim: correct beats wrong -----------------------
  # core4 & core5 both carry the correct layer -> should score as synchronous.
  correct_45 <- pair_score(stats, "core4", "core5", "synchro-test", "synchro-test")
  expect_false(is.na(correct_45))
  # core1 vs core2: correct-vs-correct must beat correct-vs-wrong.
  correct_12 <- pair_score(stats, "core1", "core2", "synchro-test", "synchro-test")
  wrong_12   <- pair_score(stats, "core1", "core2", "synchro-test", "synchro-test-wrong")
  expect_false(is.na(correct_12)); expect_false(is.na(wrong_12))
  expect_gt(correct_12, wrong_12)

  # Multi-record joint score: the all-correct combination out-scores every
  # combination that includes a "-wrong" layer.
  multi         <- stats[stats$record1 == "MULTI", ]
  multi_correct <- multi$synchronicity_score[!grepl("wrong", multi$variant1)]
  multi_wrong   <- multi$synchronicity_score[ grepl("wrong", multi$variant1)]
  expect_length(multi_correct, 1L)
  expect_gt(multi_correct, max(multi_wrong))

  # --- Loose bounds around the reference scores ------------------------------
  # Reference (Example/SyncER_outputs/synchro-test_stats.csv):
  #   core4/core5 correct ~ 0.76, core1/core2 wrong ~ 0.09, all-correct multi ~ 0.19.
  # Bounds are wide on purpose (Monte Carlo + offset tolerance); tighten to the
  # exact reproduced values once you've run this on a clean checkout.
  expect_gt(correct_45, 0.40); expect_lt(correct_45, 0.95)
  expect_lt(wrong_12, 0.25)
  expect_gt(multi_correct, 0.05); expect_lt(multi_correct, 0.45)
})

test_that("bundled run is reproducible across repeated compute calls", {
  skip_on_cran()
  dir <- find_example_dir()
  skip_if(is.na(dir),
          "Bundled record_data_input.xlsx + .out files not found; ship them in inst/extdata to enable.")

  event_stats <- build_event_stats(dir)
  expect_equal(run_compute(event_stats)$all_horizon_stats,
               run_compute(event_stats)$all_horizon_stats)
})
